TOKENSTORE_DIR = ".garmin_tokens"
DB_PATH = "garmin_data.db"
EXPORT_DIR = "exports"
BACKUP_DIR = "backups"
FETCH_BATCH_SIZE = 20
DETAIL_FETCH_DELAY_SEC = 0.5
SYNC_LOOKBACK_DAYS = 7
AUTO_BACKUP_ON_SYNC = True
BACKUP_RETENTION_COUNT = 7
GARMIN_RETRY_ATTEMPTS = 3
GARMIN_RETRY_BASE_DELAY_SEC = 15
GARMIN_RETRY_MAX_DELAY_SEC = 60
GARMIN_CIRCUIT_BREAKER_FAILURES = 3
GARMIN_CIRCUIT_BREAKER_TIMEOUT_SEC = 120
COACH_CIRCUIT_BREAKER_FAILURES = 3
COACH_CIRCUIT_BREAKER_TIMEOUT_SEC = 60

# REI component weights (must sum to 1.0 when all sensors present)
REI_WEIGHT_CADENCE = 0.30
REI_WEIGHT_OSCILLATION = 0.25
REI_WEIGHT_AEROBIC_EFF = 0.30
REI_WEIGHT_GROUND_CONTACT = 0.15

# Physiological targets for normalization
CADENCE_TARGET_SPM = 170        # full cadence (both feet); excellent ~180
OSCILLATION_TARGET_CM = 8.0     # cm; excellent ~6.5
GROUND_CONTACT_TARGET_MS = 240  # ms; excellent ~200

# AE baseline uses best N% of qualifying runs
AE_BASELINE_PERCENTILE = 20     # top 20% by aerobic efficiency
AE_BASELINE_MIN_DURATION_SEC = 1200  # 20 min minimum to count toward baseline

# Recalibrate AE baseline after this many new runs are added
AE_RECALIBRATE_AFTER_NEW_RUNS = 10

# VDOT estimation
VDOT_EFFORT_CORRECTION = 1.10
VDOT_HR_LOWER_FRACTION = 0.70
VDOT_HR_UPPER_FRACTION = 0.92
VDOT_ESTIMATE_PERCENTILE = 90
VDOT_MIN_RUN_DURATION_SEC = 1200

# RAG knowledge base
KNOWLEDGE_DIR = "knowledge"
KNOWLEDGE_DB_PATH = "chroma_db"
KNOWLEDGE_RETRIEVAL_K = 4
KNOWLEDGE_SIMILARITY_THRESHOLD = 0.4

# Coach harness compaction
COACH_WEEKLY_MILEAGE_WEEKS = 8
COACH_RECENT_RUN_LIMIT = 35
COACH_MAX_CONVERSATION_MESSAGES = 12
